### ISSUE TITLE
Transaction investigation 

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-3-preview#81]
@hal0x2328 could you take a look at this transaction to verify that its been parsed correctly? https://neo3-preview.com/transaction/0x019befa728a371a08fb0f78330b3c697ebc9d8bbf252bd173b17cc2bd6e97e9c

**Comment by ixje** [comment]
at first sight the script fields look off
![image](https://user-images.githubusercontent.com/6625537/82867530-55326e80-9f2b-11ea-9cb7-f74987dfef92.png)

**Comment by hal0x2328** [comment]
It does seem to match the code - it's the transaction that deploys the initial native tokens in the genesis block, built by this function: 
https://github.com/neo-project/neo/blob/9cbc025450f4120f795e6671da2683bfba6908b8/src/neo/Ledger/Blockchain.cs#L154

In the disassembler view it appears to use the special opcode `Neo.Native.Deploy` which is hard-coded to deploy the inital contracts which in turn send the initial NEO/GAS amounts, instead of using an embedded script to do it.

**Comment by lllwvlvwlll** [comment]
@wanglongfei88 This looks like its not an issue.
